version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        host: ${HOST}
    restart: always
    environment:
      - SERVER_NAME=${HOST}
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
